'use client';

import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Play, Sparkles, MessageSquare, ShieldCheck, BarChart3, ArrowRight } from 'lucide-react';
import { cn } from '@/lib/utils';

interface DemoModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const DemoModal = ({ isOpen, onClose }: DemoModalProps) => {
  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-black/90 backdrop-blur-2xl"
          />
          
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 40 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 40 }}
            className="relative w-full max-w-6xl bg-[#050505] border border-white/10 rounded-[4rem] overflow-hidden shadow-[0_0_100px_rgba(37,99,235,0.1)] flex flex-col lg:flex-row min-h-[70vh]"
          >
            {/* Close Button */}
            <button 
              onClick={onClose}
              className="absolute top-8 right-8 z-50 w-12 h-12 rounded-full bg-white/5 border border-white/10 flex items-center justify-center hover:bg-white/10 transition-all text-white/20 hover:text-white"
            >
              <X className="w-6 h-6" />
            </button>

            {/* Left Content */}
            <div className="flex-1 p-12 lg:p-20 relative overflow-hidden flex flex-col justify-center">
               <div className="absolute top-0 left-0 w-full h-full bg-[radial-gradient(circle_at_0%_0%,_rgba(37,99,235,0.1)_0%,_transparent_50%)]" />
               
               <div className="relative">
                  <motion.div 
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    className="inline-flex items-center gap-3 px-4 py-2 rounded-full bg-white/[0.03] border border-white/5 text-[9px] font-black uppercase tracking-[0.3em] mb-12 text-blue-400"
                  >
                     <Play className="w-3 h-3 fill-current" />
                     System Overview
                  </motion.div>
                  
                  <h2 className="text-5xl lg:text-7xl font-black tracking-[-0.05em] text-white mb-10 leading-[0.9] italic">
                    The end of <br />
                    <span className="text-white/20">manual entry.</span>
                  </h2>

                  <div className="space-y-10 max-w-md">
                     {[
                       { icon: MessageSquare, title: "Conversational Ledger", desc: "Just talk to easyKhata. Our AI detects amounts, categories, and dates instantly." },
                       { icon: BarChart3, title: "Deep Analytics", desc: "Professional P&L and Balance Sheets generated by your conversation." },
                       { icon: ShieldCheck, title: "Institutional Security", desc: "Bank-grade encryption for your digital and physical assets." }
                     ].map((item, i) => (
                       <motion.div 
                         key={i}
                         initial={{ opacity: 0, y: 10 }}
                         animate={{ opacity: 1, y: 0 }}
                         transition={{ delay: 0.3 + i * 0.1 }}
                         className="flex gap-6 group"
                       >
                          <div className="w-14 h-14 rounded-2xl bg-white/[0.02] border border-white/5 flex items-center justify-center shrink-0 group-hover:bg-blue-500/10 group-hover:border-blue-500/20 transition-all duration-500">
                             <item.icon className="w-6 h-6 text-white/20 group-hover:text-blue-400 transition-colors" />
                          </div>
                          <div>
                             <h4 className="font-black text-white text-lg tracking-tight mb-1">{item.title}</h4>
                             <p className="text-white/30 text-sm leading-relaxed font-medium">{item.desc}</p>
                          </div>
                       </motion.div>
                     ))}
                  </div>
               </div>
            </div>

            {/* Right Interactive Preview */}
            <div className="w-full lg:w-[45%] bg-[#080809] p-8 lg:p-12 flex items-center justify-center relative border-l border-white/5">
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_100%_100%,_rgba(99,102,241,0.05)_0%,_transparent_50%)]" />
                
                <div className="relative w-full max-w-[320px] aspect-[9/19] bg-[#0c0c0d] rounded-[3.5rem] border-[8px] border-[#1a1a1b] shadow-2xl overflow-hidden flex flex-col ring-1 ring-white/10">
                   {/* Phone Header */}
                   <div className="px-6 pt-10 pb-4">
                      <div className="w-full h-1 bg-white/5 rounded-full mb-6 mx-auto max-w-[40px]" />
                      <div className="flex items-center justify-between mb-8">
                         <div className="flex flex-col">
                            <span className="text-[10px] font-black uppercase tracking-[0.2em] text-white/20">Status</span>
                            <span className="text-xs font-black tracking-tight text-white/90">Syncing...</span>
                         </div>
                         <div className="w-8 h-8 rounded-full bg-blue-500/20 border border-blue-500/20 flex items-center justify-center">
                            <div className="w-2 h-2 rounded-full bg-blue-400 animate-pulse" />
                         </div>
                      </div>
                   </div>

                   {/* Phone Chat area */}
                   <div className="flex-1 px-4 space-y-4">
                      <motion.div 
                        initial={{ opacity: 0, x: 20, y: 10 }}
                        animate={{ opacity: 1, x: 0, y: 0 }}
                        transition={{ delay: 0.8 }}
                        className="bg-blue-600 px-5 py-4 rounded-[1.5rem] rounded-tr-none text-xs font-bold leading-relaxed shadow-xl"
                      >
                        "Just paid 5000 for office rent"
                      </motion.div>

                      <motion.div 
                        initial={{ opacity: 0, x: -20, y: 10 }}
                        animate={{ opacity: 1, x: 0, y: 0 }}
                        transition={{ delay: 1.2 }}
                        className="bg-white/5 border border-white/10 p-5 rounded-[1.5rem] rounded-tl-none space-y-4"
                      >
                         <div className="flex items-center gap-2 mb-1">
                            <Sparkles className="w-3 h-3 text-blue-400" />
                            <span className="text-[9px] font-black uppercase tracking-widest text-white/40">Analyzing...</span>
                         </div>
                         <div className="space-y-2">
                            <div className="flex justify-between items-end">
                               <div className="p-2 bg-white/5 rounded-lg border border-white/5">
                                  <p className="text-[8px] font-black text-white/20 uppercase tracking-widest">Amount</p>
                                  <p className="text-lg font-black tracking-tight">5,000.00</p>
                               </div>
                               <div className="p-2 bg-white/5 rounded-lg border border-white/5 text-right">
                                  <p className="text-[8px] font-black text-white/20 uppercase tracking-widest">Type</p>
                                  <p className="text-xs font-black text-red-400 uppercase tracking-widest">Expense</p>
                               </div>
                            </div>
                            <div className="p-3 bg-blue-500 rounded-xl text-[10px] font-black uppercase tracking-[0.2em] text-center shadow-lg shadow-blue-500/20">
                               Confirm Record
                            </div>
                         </div>
                      </motion.div>
                   </div>

                   {/* Phone Input */}
                   <div className="p-6 bg-gradient-to-t from-black/40 to-transparent">
                      <div className="h-12 w-full bg-white/5 border border-white/10 rounded-full px-4 flex items-center gap-3">
                         <div className="w-4 h-4 bg-white/10 rounded-full" />
                         <div className="h-2 w-24 bg-white/10 rounded-full" />
                         <div className="ml-auto w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center">
                            <ArrowRight className="w-4 h-4" />
                         </div>
                      </div>
                   </div>
                </div>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};
